## NumPy  Arrays

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [9]:
my_mat=[[1, 2, 3], [4, 5, 6],[7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [20]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.76215813, 0.25199732, 0.86203664, 0.54915416, 0.84896284])

In [23]:
np.random.rand(5,5)

array([[0.78463707, 0.26134813, 0.68957899, 0.04546932, 0.0407835 ],
       [0.25556273, 0.09572105, 0.30739571, 0.10943772, 0.10598878],
       [0.0647276 , 0.09249207, 0.73169614, 0.51535048, 0.91411555],
       [0.54238337, 0.43592461, 0.33621656, 0.95377487, 0.63583895],
       [0.87960352, 0.64018675, 0.33073927, 0.13129011, 0.03066415]])

In [24]:
np.random.randn(2)

array([-0.92710515, -1.22627508])

In [25]:
np.random.randn(4,4)

array([[ 0.63737165, -0.17314099, -0.24517614, -1.76271779],
       [-1.30184891, -0.55023988, -0.56182211, -0.01608018],
       [-0.59241827,  1.7677751 ,  0.04618526, -1.65152221],
       [ 0.42768486,  0.13245504,  0.21186548,  0.36961579]])

In [26]:
np.random.randint(1,100)

96

In [27]:
np.random.randint(1, 100, 10)

array([89, 62, 33, 15, 91, 86, 27, 79, 72, 75])

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr =  np.random.randint(0, 50, 10)

In [31]:
ranarr

array([19, 29, 33, 36, 41, 22, 44, 39, 39,  6])

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr.max()

44

In [34]:
ranarr.min()

6

In [35]:
ranarr

array([19, 29, 33, 36, 41, 22, 44, 39, 39,  6])

In [36]:
ranarr.argmax()

6

In [37]:
ranarr.argmin()

9

In [44]:
arr.shape

(25,)

In [45]:
arr = arr.reshape(5,5)

In [46]:
arr.shape

(5, 5)

In [47]:
arr.dtype

dtype('int32')